// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FilterDirectFlightTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filterDirectFlight() {
    // Test name: FilterDirectFlight
    // Step # | name | target | value
    // 1 | open | /ca/en/aco/home.html | 
    driver.get("https://www.aircanada.com/ca/en/aco/home.html");
    // 2 | setWindowSize | 1440x791 | 
    driver.manage().window().setSize(new Dimension(1440, 791));
    // 3 | runScript | window.scrollTo(0,286) | 
    js.executeScript("window.scrollTo(0,286)");
    // 4 | click | id=bkmgFlights_origin_trip_1 | 
    driver.findElement(By.id("bkmgFlights_origin_trip_1")).click();
    // 5 | click | css=.ac-icon_cross | 
    driver.findElement(By.cssSelector(".ac-icon_cross")).click();
    // 6 | click | id=bkmgFlights_origin_trip_1 | 
    driver.findElement(By.id("bkmgFlights_origin_trip_1")).click();
    // 7 | type | id=bkmgFlights_origin_trip_1 | tor
    driver.findElement(By.id("bkmgFlights_origin_trip_1")).sendKeys("tor");
    // 8 | click | css=#bkmgFlights_origin_trip_1SearchResult0 .abc-ripple-wrapper | 
    driver.findElement(By.cssSelector("#bkmgFlights_origin_trip_1SearchResult0 .abc-ripple-wrapper")).click();
    // 9 | click | id=bkmgFlights_destination_trip_1 | 
    driver.findElement(By.id("bkmgFlights_destination_trip_1")).click();
    // 10 | click | css=.abc-input-clear-button | 
    driver.findElement(By.cssSelector(".abc-input-clear-button")).click();
    // 11 | type | id=bkmgFlights_destination_trip_1 | new
    driver.findElement(By.id("bkmgFlights_destination_trip_1")).sendKeys("new");
    // 12 | click | css=#bkmgFlights_destination_trip_1SearchResult1 .abc-ripple-wrapper | 
    driver.findElement(By.cssSelector("#bkmgFlights_destination_trip_1SearchResult1 .abc-ripple-wrapper")).click();
    // 13 | click | id=bkmgFlights_travelDates_1-formfield-1 | 
    driver.findElement(By.id("bkmgFlights_travelDates_1-formfield-1")).click();
    // 14 | runScript | window.scrollTo(0,773) | 
    js.executeScript("window.scrollTo(0,773)");
    // 15 | click | css=#bkmgFlights_travelDates_1-date-2022-03-01 > .date | 
    driver.findElement(By.cssSelector("#bkmgFlights_travelDates_1-date-2022-03-01 > .date")).click();
    // 16 | click | css=#bkmgFlights_travelDates_1-date-2022-03-08 > .date | 
    driver.findElement(By.cssSelector("#bkmgFlights_travelDates_1-date-2022-03-08 > .date")).click();
    // 17 | click | css=#bkmgFlights_travelDates_1AbcCalendarDialogCloseButton .abc-ripple-wrapper | 
    driver.findElement(By.cssSelector("#bkmgFlights_travelDates_1AbcCalendarDialogCloseButton .abc-ripple-wrapper")).click();
    // 18 | mouseOver | css=#bkmgFlights_travelDates_1AbcCalendarDialogCloseButton .abc-ripple-wrapper | 
    {
      WebElement element = driver.findElement(By.cssSelector("#bkmgFlights_travelDates_1AbcCalendarDialogCloseButton .abc-ripple-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | click | css=#bkmgFlights_findButton .abc-ripple-wrapper | 
    driver.findElement(By.cssSelector("#bkmgFlights_findButton .abc-ripple-wrapper")).click();
    // 20 | waitForElementVisible | id=flightBlockMainTitle | 15000
    {
      WebDriverWait wait = new WebDriverWait(driver, 15);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("flightBlockMainTitle")));
    }
    // 21 | click | css=#sortByDuration span:nth-child(2) | 
    driver.findElement(By.cssSelector("#sortByDuration span:nth-child(2)")).click();
    // 22 | click | css=#cabinBtnECO70 .fare-details-section | 
    driver.findElement(By.cssSelector("#cabinBtnECO70 .fare-details-section")).click();
    // 23 | click | css=.fare-features-content:nth-child(2) .btn > span | 
    driver.findElement(By.cssSelector(".fare-features-content:nth-child(2) .btn > span")).click();
    // 24 | runScript | window.scrollTo(0,266.5) | 
    js.executeScript("window.scrollTo(0,266.5)");
    // 25 | click | css=#sortByDuration > .sort-button | 
    driver.findElement(By.cssSelector("#sortByDuration > .sort-button")).click();
    // 26 | click | css=#cabinBtnEXEC101 .fare-amount > .display-on-hover | 
    driver.findElement(By.cssSelector("#cabinBtnEXEC101 .fare-amount > .display-on-hover")).click();
    // 27 | click | css=.premium-body-cabin:nth-child(2) .btn | 
    driver.findElement(By.cssSelector(".premium-body-cabin:nth-child(2) .btn")).click();
    // 28 | runScript | window.scrollTo(0,345.5) | 
    js.executeScript("window.scrollTo(0,345.5)");
    // 29 | click | css=.bounds-container > .title-level-two > span:nth-child(2) | 
    driver.findElement(By.cssSelector(".bounds-container > .title-level-two > span:nth-child(2)")).click();
    // 30 | assertText | css=.bounds-container > .title-level-two > span:nth-child(2) | Flight summary
    assertThat(driver.findElement(By.cssSelector(".bounds-container > .title-level-two > span:nth-child(2)")).getText(), is("Flight summary"));
  }
}
